export const serviceSquadList = {
  team: 'Omni Bulls',
  squads: [
    {
      Id: 1,
      Name: 'Arquitetura',
      Description: 'Manter a arquitetura do projeto funcionando, performando e com qualidade.',
      Manager: 'Yano',
      Collaborators: [
        {
          Id: 1,
          Name: 'Adriano Mendes',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'adriano.mendes@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Eloi Rodrigues',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'eloi.rodrigues@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter a arquitetura do projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Lucas Magalhães',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'Apoiar nos desafios técnicos e orientar evolução de carreira e habilidades',
          Email: 'lucas.magalhaes@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Apoio técnico',
        },
        {
          Id: 4,
          Name: 'Douglas Silva',
          Office: 'Desenvolvedor FrontEnd',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2008,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'douglas.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter a arquitetura do projeto, desenvolver novas features e dar manutenção no sistema',
        },
        {
          Id: 5,
          Name: 'Fernanda Sonata',
          Office: 'Desenvolvedor FrontEnd',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2014,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'fernanda.sonata@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter a arquitetura do projeto, desenvolver novas features e dar manutenção no sistema',
        },
        {
          Id: 6,
          Name: 'William Machado',
          Office: 'Desenvolvedor FrontEnd',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2021,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'william.machado@db1.com.br',
          Location: 'São Paulo (Capital)',
          Responsibilities: 'Manter a arquitetura do projeto, desenvolver novas features e dar manutenção no sistema',
        },
        {
          Id: 7,
          Name: 'Júlia Yto',
          Office: 'Quality Assurance',
          Project: 'Omni Bulls',
          Squad: 'Arquitetura',
          Company: 'DB1',
          Hired: 2017,
          Skills: 'Testes de fluxos e serviços',
          Email: 'julia.yto@db1.com.br',
          Location: 'Santa Catarina (Capital)',
          Responsibilities: 'Manter a arquitetura do projeto, desenvolver testes manter o sistema',
        },
      ]
    },
    {
      Id: 2,
      Name: 'Segurança',
      Description: 'Teste 1 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 2',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Segurança',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Segurança',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Segurança',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
    {
      Id: 3,
      Name: 'Regulatório',
      Description: 'Teste 2 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 3',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Regulatório',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Regulatório',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Regulatório',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
    {
      Id: 4,
      Name: 'Operação',
      Description: 'Teste 3 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 4',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Operação',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Operação',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Operação',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
    {
      Id: 5,
      Name: 'Sustentação',
      Description: 'Teste 4 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 5',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Sustentação',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Sustentação',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Sustentação',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
    {
      Id: 6,
      Name: 'Negócios',
      Description: 'Teste 5 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 6',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Negócios',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Negócios',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Negócios',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
    {
      Id: 7,
      Name: 'Serviço Bancário e Negócios PJ',
      Description: 'Teste 6 Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI.',
      Manager: 'Teste 7',
      Collaborators: [
        {
          Id: 1,
          Name: 'Teste Silva',
          Office: 'Gestor',
          Project: 'Omni Bulls',
          Squad: 'Serviço Bancário e Negócios PJ',
          Company: 'DB1',
          Hired: 2018,
          Skills: 'Gerir projetos e pessoas',
          Email: 'teste.silva@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Gestão de pessoas e projeto',
        },
        {
          Id: 2,
          Name: 'Teste Vieira',
          Office: 'Líder Técnico',
          Project: 'Omni Bulls',
          Squad: 'Serviço Bancário e Negócios PJ',
          Company: 'Omni',
          Hired: 2013,
          Skills: 'Gerir squad de arquitetura',
          Email: 'teste.vieira@omni.com.br',
          Location: 'São Paulo (Campinas)',
          Responsibilities: 'Manter o projeto com qualidade e em evolução',
        },
        {
          Id: 3,
          Name: 'Teste Santos',
          Office: 'Tech Leader',
          Project: 'Omni Bulls',
          Squad: 'Serviço Bancário e Negócios PJ',
          Company: 'DB1',
          Hired: 2015,
          Skills: 'React Native, React Js, Angular, Jest, Java Script, Type Script, ...',
          Email: 'teste.santos@db1.com.br',
          Location: 'Paraná (Maringá)',
          Responsibilities: 'Manter o projeto, desenvolver novas features e dar manutenção no sistema',
        },
      ]
    },
  ]
};
